Vagrant.configure("2") do |config|

  config.vm.provision "docker" do |d|
    d.build_image "/vagrant", args: "-t salt-sumo-events"
    d.run "salt-sumo-events", args: "--env-file /vagrant/env_file.txt -p 4505:4505 -p 4506:4506 -p 5985:5985 -p 5986:5986 -p 8000:8000", cmd: "#{hostname}.vistaprint.net"
  end

  config.vm.box = "ubuntu/xenial64"

  config.vm.synced_folder "..", "/vagrant"
 
end